package com.securenotes.model;

import jakarta.persistence.*;
import lombok.Data;

@Entity
@Data
public class Token {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int tokenId;

    private String token;
    private String refreshToken;

    @ManyToOne//many tokens can be generated by a user
    @JoinColumn(name="userId")//foreign key
    private User user;

    private boolean isLoggedOut;

}
